# Generated by Django 3.0.7 on 2020-07-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roboy', '0002_auto_20200709_1247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_signup',
            new_name='create_user',
        ),
    ]
