# Generated by Django 3.0.7 on 2020-07-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboy', '0004_auto_20200712_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
