# Generated by Django 3.0.7 on 2020-07-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboy', '0005_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='images',
        ),
    ]
