# Generated by Django 3.0.7 on 2020-07-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roboy', '0007_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='emailid',
            new_name='email',
        ),
    ]
