# Generated by Django 3.0.7 on 2020-07-15 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roboy', '0008_auto_20200715_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='phonenumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
