# Generated by Django 3.0.7 on 2020-07-15 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roboy', '0009_user_details_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_images',
            name='caption',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
